### ISSUE TITLE
Intro to Responsive Design check-in 

### ISSUE THREAD

**Issue by sbchittenden** [plosty/learning-web-components#1]
@plosty 

Hi Phil -

I got an email that you wanted a interim check-in on your portfolio work so far. I had a look through and it looks as though it is coming along nicely 👍 

Right now your inline click handlers on the carousel dots and the "previous" and "next" arrows are throwing an Reference Error. Because you have them inlined _and_ you have your `portfolio.js` scoped in the anonymous IIFE your `plusSlides` and `currentSlides` functions can't be accessed (as they are "hidden" inside the IIFE). You can either ditch the IIFE _or_ ditch the inlined JS (recommended :) ). 

I will hold off on offering any other comments since it is obvious that you are still building and rearranging things. If there is anything in particular you want me to take a look at or have questions about feel free to hit me up.

-Sam

**Comment by plosty** [comment]
@sbchittenden - thanks for the quick feedback! I just actually checked in quite a few fixes I've been working on, which hopefully resolves a lot of issues. Sorry for jumping the gun with my email!

At the moment I am just concentrating on getting things working on the mobile view (up to 360px) then I plan on modifying it for the larger screens.

Cheers,

Phil

**Comment by sbchittenden** [comment]
@plosty 

Cool beans. Like I said, let me know if you want a second set of eyes on anything specific.

-Sam
